### ISSUE TITLE
j.clients.corex (JSX enablement) [development_corex]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/corex#2]
- still called tfmux?
- move python client to JSX 

# make sure following done

- [x] builder build the corex server parts
- [x] start command in builder running in foregeground (not using tmux)
- [x] j.clients.corex talks to the corex
- [ ] check there is security in the corex (at least a secret, if not talk to maxim) 
- [x] builder has some test method using the j.clients.corex

# remarks

- don't use config management !!! otherwise chicken and egg problem
- branch: development_corex

**Comment by despiegk** [comment]
check with reem/christophe/maxux

**Comment by maxux** [comment]
Please see branch `development_corex`, mostly everything is there.
I'm checking about security, it was out-of-box using original `ttyd` and I didn't changed anything related to that, I'm checking.

**Comment by despiegk** [comment]
has been merged in development_installer as well

**Comment by despiegk** [comment]
put some extra docu in

**Comment by despiegk** [comment]
there are other FR/ISSUES to do more of the details
